### ISSUE TITLE
url works in 0.3.12, but returns 404 in 0.4.2

### ISSUE THREAD

**Issue by ianshmean** [JuliaWeb/Requests.jl#91]
I have a https url I'm trying to `get` and in 0.4.2 it's returning a 404 error, whereas in 0.3.12 it functions as expected. Curiously this only occurs for the domain I'm using (https and http work for google etc. in both)

0.3.12
```
> println(get("https://www.firebaseio.com/"))                                                                                                                              
Response(200 OK, 13 Headers, 703 Bytes in Body)
```

0.4.2
```
> println(get("https://www.firebaseio.com/"))                                                                                                                              
Response(404 Not Found, 7 headers, 9 bytes in body)
```

**Comment by ianshmean** [comment]
Just to add context, both of these were after a `Pkg.update()` on a fresh JuliaBox session

**Comment by malmaud** [comment]
This should be fixed in master.

**Comment by ianshmean** [comment]
I've tried checking out master (0.3.3+) and the issue remains in 0.4.2. 
I can only check through JuliaBox currently, but I am able to ping the domain through the juliabox console, so I assume the issue isn't specific to juliabox(?)

```
> println(get("https://www.firebaseio.com/"))
Response(404 Not Found, 7 headers, 9 bytes in body)

> println(get("https://google.com"))
Response(200 OK, 17 headers, 18978 bytes in body)
```

**Comment by ianshmean** [comment]
Correction. It does work! 
Curiously the juliabox instance required a restart for the update to Requests to come into effect, even though `Pkg.status()` was reporting the master version of Requests.

Thanks
